### PR TITLE
Update Profile.ts

### PR DESCRIPTION
**Pull request by Hiroto77**

### CODE REVIEW

**Comment by Hiroto77** [comment]
@AlenSaito1

**Review by PrajjwalDatir — APPROVED** [review]

**Comment by PrajjwalDatir** [comment]
Fixed a typo @AlenSaito1  🚀

**Comment by Hiroto77** [comment]
> Fixed a typo @AlenSaito1  🚀 

So shall i close this now?

**Comment by PrajjwalDatir** [comment]
> So shall i close this now?

😄 No, Don't close it. @AlenSaito1 will merge it. You don't need to do anything.

**Pull request merged**
